### PR TITLE
Extend user config to allow fine-grain class override

### PR DESCRIPTION
**Pull request by xguerin**
Improve the integration of Grid.js in heavily class-based framework (like Bootstrap) by enable finer grained class extension points in user config.

### CODE REVIEW

**Comment by afshinm** [comment]
Hey @xguerin! 

Is it not possible to use CSS child selectors instead of assigning classNames to child directly?

**Comment by xguerin** [comment]
My original was indeed to do all on CSS but my understanding is that I cannot append classe names to a node using CSS. 

I can do that in JS without changing gridjs by appending classes on `beforeLoad` and `ready` events but that results in unfortunate flickers since the UI is basically rendered twice by the browser (once without the toolkit classes and once with).

That being said I’m not an expert so any suggestion is appreciated.

**Comment by afshinm** [comment]
Right, but let's say you need to customize the `thead` node, you can do something like this:

```js
new Grid({
  columns: ['Name', 'Email', 'Phone Number'],
  search: true,
  data: [
    ['John', 'john@example.com', '(353) 01 222 3333'],
    ['Mark', 'mark@gmail.com',   '(01) 22 888 4444'],
    ['Eoin', 'eo3n@yahoo.com',   '(05) 10 878 5554'],
    ['Nisen', 'nis900@gmail.com',   '313 333 1923']
  ],
  className: {
    table: 'custom-table-classname'
  }
});
```

and in your CSS:

```
.custom-table-classname thead {
  background-color: red;
}
```

does that work for you?

**Comment by xguerin** [comment]
I don't believe that would be enough.

For example, Boostrap allows to [specify different kind of styles for a table header](https://getbootstrap.com/docs/4.5/content/tables/#table-head-options). I need a way to pass the `thead-light` class, for instance, to the `<thead/>` element.

Another example is the pagination buttons. If I want to integrate them in bootstrap, I need to specify the `btn-group` class to the enclosing `<div>` and the `btn` class to the button themselves. I don't think I can do that with CSS.

**Comment by afshinm** [comment]
Oh, I see. yeah that makes sense. Alright, I'm going to review this PR soon. thanks @xguerin

**Comment by afshinm** [comment]
Sorry for the delay @xguerin. I will review this PR in the next few days.

**Comment by afshinm** [comment]
I just rebased this PR https://github.com/grid-js/gridjs/pull/370 -- also flattened the className list and added some more tests. I will merge that PR soon.

**Pull request closed without merging**
